config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a target="_blank" href="https://www.linkedin.com/in/muhammad-ibraheem-04468321a">Muhammad Ibraheem </a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "about", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
  <div class='alert alert-<%="#{name}" %>'>
    <a href="#" class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to "Users", users_path, class: 'nav-link' %>
          </li>
<% if logged_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "New Article", new_article_path, class:"dropdown-item" %>
        <%= link_to "Create new Category", new_category_path, class: "dropdown-item" %> 
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>

<% end %>

<li class="nav-item">
  <%= link_to "Categories" , categories_path, class: 'nav-link' %>
  </li>






      <% if logged_in? %>
      <li class="nav-item">
      <% if current_user.admin? %>
        <%= link_to "Your profile Admin" , user_path(current_user), class:"nav-link" %>
        <% else link_to "Your profile", user_path(current_user), class:"nav-link" %>
        <% end %>
      </li>


      <li class="nav-item">
        <%= link_to "Edit your profile", edit_user_path(current_user), class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "View your profile", user_path(current_user), class:"nav-link" %>
      </li>


      <li class="nav-item">
        <%= link_to "Log out", logout_path, class: 'nav-link', method: :delete %>
        </li>
         <% else %>
         <%= link_to "Log in", login_path, class: 'nav-link' %>
         <%= link_to "Sign up", signup_path, class: 'nav-link' %>
         <% end %>



    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
   <%= yield %>
   </div>
   <%= render 'layouts/footer' %>
</body>
</html>